permalink: /:title

collections:
  models:
    output: true
  updates:
    output: true

defaults:
  - scope:
      path: ""
      type: "models"
    values:
      layout: "model-post"
  - scope:
      path: ""
      type: "updates"
    values:
      layout: "update-post"