permalink: /:title

collections:
  models:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "models"
    values:
      layout: "model-post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "update-post"