#- {name: 'name', url: 'url'} #url is found in page
menu:
#- {name: 'Home', url: ''}
- {name: 'Model list', url: 'model-list'}
- {name: 'Updates', url: 'updates'}
#- {name: 'Favorite models', url: 'favorites' }
#- {name: 'My OCs', url: 'characters' }


# Customize site text
pagination:
  next_page: '>>'
  previous_page: '<<'
